spring:
  application:
    name: movie
  data:
    mongodb:
      database: movie
      host: ${DB_HOST:localhost}

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
---
spring:
  profiles: docker
  data:
    mongodb:
      database: movie
      host: moviedb

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
