spring:
  application:
    name: movie

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/